---
title: "Members"
description: |
  An R consortium community to support R users in government
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### R-Govys Groups and R Users Groups

Inter-agency R Users Group - a cross-agency R Users group in the US federal agencies to promote training and event information dissemination across agencies.

BLS R Users Group

NMFS R Users Groups - Facilitating R trainings and support for R users in NOAA Fisheries. The following centers have active R User groups.
* SWFSC R User Group - Southwest Fisheries Science Center
* AFSC R User Group - Alaska Fisheries Science Center

### R-Govys Contacts

**Wendy Martinez**

**E. Eli Holmes** is a research scientist with NOAA Fisheries. She is an applied mathematician who works on algorithms for multivariate state-space analysis of time series data. She is active in R and open-science training in NOAA Fisheries. [Webpage](https://eeholmes.github.io) [GitHub](https://github.com/eeholmes)

**Donna LaLonde**

**Add more**





