---
title: "NMFS R Users Meetings"
description: |
  NMFS R Users Group
author:
  - name: Emily Markowitz
    url: https://emilyhmarkowitz.github.io/emilyhmarkowitz/
    affiliation: NOAA Fisheries, AFSC
date: 10-12-2021
output:
  distill::distill_article:
    self_contained: false
categories:
  - nmfs-r-users
  - rmarkdown
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Join the NMFS R Users Group

We have monthly meetings on topics of interests to R users in our agency. Info and upcoming events here: https://nmfs-openscapes.github.io/NMFS-R-UG/

Sign up for our email list:
Make sure you are logged into your NOAA Google account in your browser. Then click [sign-up for NMFS R UG](https://docs.google.com/spreadsheets/d/1WwiGAf7Lmrx3sdrif3R-IhIJiXUIFBHydloixY6fWuo/edit#gid=0) to see the event and add to your calendar.

## Oct 2021 Inaugural meeting of the NMFS R Users Group! 

Agenda for the October 12, 2021 Meeting: Getting organized and a short cool topic presentation.

1. What do we want this R Users group to do? Suggestions: 

   - All things R across all of NOAA Fisheries
   - 15 minute talks on cool topics
     - Tutorial sharing 
     - Lightning talks
     - Discussions on best practices
   - Reading group
   - Tidy Tuesday challenges
   - Breakout groups/brainstorming/hack-a-thons for developing better workflows/products

2. Topics we would like to see discussed this quarter. Examples:

   - {Targets} - Tutorial
   - {NMFSReports} - can we work on something like this together to help standardize our annual report writing processes across NMFS?	     
   - Lightning talks about how we write reports with R Markdown. Pros and Cons?	Presentation + Discussion
   - {testthat} - Tutorial
   - {googledrive} - Tutorial
   - What should be shared on GitHub - discussion about best practices and caveats

3. How often we would like to meet.

### How to see the meeting info

Instructions to see the virtual meeting link and shared documents. 

Make sure you are logged into your NOAA Google account in your browser. Then click [the calendar event](https://calendar.google.com/event?action=TEMPLATE&tmeid=MG05MWM5ZmdzZDYxOTY5Ym9sMzI1c2JkYnMgbm9hYS5nb3ZfNjByZm43bWw5cnBjaGw2M3ZzNGFmOW4wMThAZw&tmsrc=noaa.gov_60rfn7ml9rpchl63vs4af9n018%40group.calendar.google.com) to see the event and add to your calendar.

Alternative instructions:

Go to the Events tab. In the top right, you'll see a little arrow. Click that and make sure you can see the NMFS R Users calendar. If you can, then click on the event on Oct 12th, 2021 and click on 'show details' in the event pop-up. *I can't see the NMFS R Users calendar*. You need to be logged into your NOAA Google account in your browser. *I don't have a NOAA email* NMFS = National Marine Fisheries Service. This is a NOAA Fisheries R User group. You can join the Inter-Agency R Users Group if you are in a different US federal agency.
